### ISSUE TITLE
Content-Length must contain only digits

### ISSUE THREAD

**Issue by sotero73** [mylisabox/flutter_mjpeg#41]
Hi, first I would like to thank you for developing this library. Theoretically, it's exactly what I need. However, the MJPEG stream I have from the camera opens normally in the browser but the error "Content-Length must contain only digits" appears in the library. I just provide the mjpeg stream url... what is this error exactly?
The url is in this format  https://{server}:8100/Mjpeg/1?authToken={token}

**Comment by jaumard** [comment]
Hey! Thanks for your feedback! Content length is something sent by the server, maybe it try to send a value that doesn't contain digits? Web browser may don't care ^^ maybe try to check what's inside the header of your mjpeg server. 

Can't help a lot without access to the stream itself

**Comment by cybrox** [comment]
@sotero73 Some additional info: This exception is not caused by `flutter_mjpeg` but the dart `http` client ([here](https://github.com/dart-lang/sdk/blob/9b67562b4d916bddf3834915630f1dfebe84ba88/sdk/lib/_http/http_headers.dart#L379)). According to [RFC9110 8.6](https://www.rfc-editor.org/rfc/rfc9110.html#name-content-length) _The "Content-Length" header field indicates the associated representation's data length as a decimal non-negative integer number of octets._

So yes, as was suggested, check the response of your server using `curl` or a similar tool. It looks like the server sends back bogus data in the `Content-Length` header.

**Comment by sotero73** [comment]
You're right. I tested it with postman and it returned the following error "Parse Error: There seems to be an invalid character in the "Content-Length" response header".
The problem is that I can't solve this because I can't change this information on the server. I will have to use the hls stream instead of mjpeg. Thanks.

**Comment by jaumard** [comment]
Sorry to hear that. Good luck!  You might also try to create a quick proxy for the stream and fix the wrong header. That would make it a valid stream.
